NAME=proj5

commands:
	latex $(NAME).tex
	latex $(NAME).tex
	dvips $(NAME).dvi
	ps2pdf $(NAME).ps

clean:
	rm $(NAME).ps $(NAME).aux $(NAME).log $(NAME).pdf $(NAME).dvi $(NAME).nav $(NAME).out $(NAME).snm $(NAME).toc